language: nodejs
node_js: '6'
services:
- mongodb
env:
  global:
  - secure: ZXdUMP+8Nk9Kd5nX31D/DIB1t2xlJd+T4W7umWjwpy+KPA9d1W1OhUG6V2Gpv3PsJf+UtMosgZsywcLFVG4l/WcjAhs3c9pegW5ZRYAEfVjkk7aHhWQGvj5DID8iAAxs91Mm8LwJ43o68x+XN6746zArPqcVzQltDunJ0G3gfh8=
branches:
  except:
  - gh-pages
before_install:
- openssl aes-256-cbc -K $encrypted_2b5a1ad4da99_key -iv $encrypted_2b5a1ad4da99_iv
  -in deploy-key.enc -out deploy-key -d
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa
- sudo bash ./bin/countly.install_travis.sh
install: sudo npm install
before_script:
- nodejs --version
- mongod --version
- cat /var/log/mongodb/mongod.log
- until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
script: sudo npm test
after_script:
- cat log/countly-api.log
- cat log/countly-dashboard.log
- cat /var/log/mongodb/mongod.log
after_success:
- cd $TRAVIS_BUILD_DIR
- ssh deploy@128.199.45.30 'bash -s' < bin/scripts/deploy.sh
- chmod +x bin/scripts/generateDocs.sh
- bash bin/scripts/generateDocs.sh
notifications:
  email: hello@count.ly
  slack:
    secure: SplZFh0l8fP/FuQyoFXLE4k358ERYMVaK5nxJhrGbiG08wtTrtJi0qVrEUjfNed4crWtFpvLML0Lb1P+BAykWeEWFz5rjSZ1y0mu+Uqw89D5bk7kUguk+ZF/HOD4bsls2oMRpbK3M26/1VMd6LSg/pJIQd/o8CWSnhozMemB9Pc=
