language: nodejs
node_js:
  - "4.2"
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
before_install: sudo bash ./bin/countly.install.travis.sh
install: sudo npm install
before_script:
  - mongod --version
  - cat /var/log/mongodb/mongod.log
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
script: npm test
after_script: cat /var/log/mongodb/mongod.log
notifications:
  email: hello@count.ly
  hipchat:
    rooms:
      secure: aINedM9Exa+83NKGsgpSmEWBqEY68jD9cKKUZ3m5yNxc373E2U76+nFFkaBEGayJ2stExyHicxGphIq127m8IopjG4DX/bSD8pogtIfGIklb6tz/XQafm/gGkgN2G9SVi/ef0yRisvX01jRRVU+BENQ3G4T6s6iYjoWqvQPCjpE=
