language: nodejs
node_js: "6"
services:
  - mongodb
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
before_install: sudo bash ./bin/countly.install_travis.sh
install: sudo npm install
before_script:
  - nodejs --version
  - mongod --version
  - cat /var/log/mongodb/mongod.log
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
script: npm test
after_script: 
  - cat log/countly-api.log
  - cat log/countly-dashboard.log
  - cat /var/log/mongodb/mongod.log
notifications:
  email: hello@count.ly
  slack:
    secure: SplZFh0l8fP/FuQyoFXLE4k358ERYMVaK5nxJhrGbiG08wtTrtJi0qVrEUjfNed4crWtFpvLML0Lb1P+BAykWeEWFz5rjSZ1y0mu+Uqw89D5bk7kUguk+ZF/HOD4bsls2oMRpbK3M26/1VMd6LSg/pJIQd/o8CWSnhozMemB9Pc=
