language: nodejs
node_js: "8"
services:
  - mongodb
env:
  - CXX=g++-4.8
branches:
  except:
    - gh-pages
env:
  global:
    - secure: ZXdUMP+8Nk9Kd5nX31D/DIB1t2xlJd+T4W7umWjwpy+KPA9d1W1OhUG6V2Gpv3PsJf+UtMosgZsywcLFVG4l/WcjAhs3c9pegW5ZRYAEfVjkk7aHhWQGvj5DID8iAAxs91Mm8LwJ43o68x+XN6746zArPqcVzQltDunJ0G3gfh8=
addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
install: sudo bash ./bin/countly.install_travis.sh
before_script:
  - nodejs --version
  - mongod --version
  - cat /var/log/mongodb/mongod.log
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
  - sleep 10
script: sudo npm test
after_script: 
  - cat log/countly-api.log
  - cat log/countly-dashboard.log
  - cat /var/log/mongodb/mongod.log
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x bin/scripts/generateDocs.sh
  - bash bin/scripts/generateDocs.sh
notifications:
  email: hello@count.ly
  slack:
    secure: SplZFh0l8fP/FuQyoFXLE4k358ERYMVaK5nxJhrGbiG08wtTrtJi0qVrEUjfNed4crWtFpvLML0Lb1P+BAykWeEWFz5rjSZ1y0mu+Uqw89D5bk7kUguk+ZF/HOD4bsls2oMRpbK3M26/1VMd6LSg/pJIQd/o8CWSnhozMemB9Pc=
